;
;   Reto:         
;   Andrés Rodríguez Cantú 
;   
;   Copyright (C) Tecnólogico de Monterrey
;   
;   File: platformio.ini
;   
;   Created:                   22/09/2026
;   Last Modified:             22/09/2026
;

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags = 
	-std=gnu++20        ; Para <format> y <span>
lib_extra_dirs = lib
