;
;   Reto:         
;   Andrés Rodríguez Cantú 
;   
;   Copyright (C) Tecnólogico de Monterrey
;   
;   File: platformio.ini
;   
;   Created:                   22/09/2026
;   Last Modified:             22/09/2026
;

[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino
monitor_speed = 115200
upload_speed = 921600

; Stable version of the ESP8266 core for Arduino
build_flags = 
    -std=gnu++17

lib_extra_dirs = lib